#ifndef EXECUTOR_COMMAND_LIST_H
#define EXECUTOR_COMMAND_LIST_H

enum class ExectorCommand
{
  SHUT_DOWN = 0,
  SEND_TO_ROBOT = 1,
  SEND_TO_RCA = 2,
  SEND_TO_SENSOR = 3,
  RECV_FROM_SENSOR = 4,

  INVALID = -1
};

#endif // EXECUTOR_COMMAND_LIST_H